### ISSUE TITLE
Add tags feature

### ISSUE THREAD

**Issue by MorezMartin** [Temeez/wagtail-simple-gallery#11]
Hello
I added tags feature.
It is not perfect and i am not used to work with git
Here the link if you want to integrate it
https://github.com/MorezMartin/wagtail-simple-gallery-with-tags

Sincerely yours,
Martin

**Comment by NaakkaDev** [comment]
Hello, sorry for taking so long to respond, been very busy. Thanks for the #12 pull request.

**Comment by MorezMartin** [comment]
Hello,
No problem me too ! Thanks to you, it is one of my first PR
Have a nice evening
