### ISSUE TITLE
Page type "Simple Gallery Index" is called "Gallery Index"

### ISSUE THREAD

**Issue by JOJ0** [Temeez/wagtail-simple-gallery#14]
Am I right that there is a tiny typo in the readme? Page type "Simple Gallery Index" is actually called "Gallery Index". Correct? Or is something wrong with my installation?

If I'm right, I'll send you a PR.

best,
Jojo

**Comment by JOJ0** [comment]
Yep, you defined that in class meta of SimpleGalleryIndex class:

```
    class Meta:
        verbose_name = _('Gallery index')
        verbose_name_plural = _('Gallery indices')
```

**Comment by NaakkaDev** [comment]
If I remember correctly, the reason it says "Simple Gallery Index" in the readme is because the class is called "SimpleGalleryIndex". Perhaps the verbose names in the class meta should be _('Simple Gallery Index') instead of what it is now. Feel free to PR.
