### ISSUE TITLE
Support for wagtail 1.8/1.9 

### ISSUE THREAD

**Issue by frague59** [Temeez/wagtail-simple-gallery#2]
Hi, 

I'm currently working on a 1.9 wagtail site, have you projected to support it ?
I can look at the code and may be do the job and propose a pull request...

Thanks !

**Comment by NaakkaDev** [comment]
I haven't yet, but I think I have time to do that today or tomorrow at latest. Thanks for reminding me!

**Comment by frague59** [comment]
Thanks !

**Comment by NaakkaDev** [comment]
Alright, managed to update the package after few fails. I saw now problems with the code using wagtail 1.9 so I just updated the version and setup.py.
