### ISSUE TITLE
Wagtail 6.x not supported due to requirements.txt

### ISSUE THREAD

**Issue by treefish** [Temeez/wagtail-simple-gallery#24]
The usual upgrade cycle, sorry. I'm trying to install this package, but I'm using Wagtail v6.1.1. The error on a build (I'm using Docker) is:

22.00 ERROR: Cannot install -r /requirements.txt (line 15) and wagtail<6.9 and >=6.0 because these package versions have conflicting dependencies.
22.00
22.00 The conflict is caused by:
22.00     The user requested wagtail<6.9 and >=6.0
22.00     wagtail-simple-gallery 0.10.0 depends on wagtail<6.0 and >=2.5
22.00
22.00 To fix this you could try to:
22.00 1. loosen the range of package versions you've specified
22.00 2. remove package versions to allow pip attempt to solve the dependency conflict

I know there are some changes in Wagtail that might not simply allow an increase in the Wagtail version in requirements.txt, but maybe it would be that simple?

I'm a bit new with this stuff, but would be willing to have a go at testing Wagtail 6.x compatibility and creating a fix. First time trying something like this, so please bear with me (newbie).

Extra comment: 

I wonder if it might be a reasonably easy fix. I see you've got tests for the imports of some Wagtail features in models.py, e.g.:

try:
    from wagtail.admin.edit_handlers import FieldPanel
except ImportError:
    from wagtail.admin.panels import FieldPanel

So maybe that's already enough to support Wagtail 6.x? I know there were some changes to where these classes like FieldPanel were moved, going from Wagtail 4 - 5.

**Comment by NaakkaDev** [comment]
Hey, thanks for poking me as I don't currently follow the Wagtail development so I don't know when a new version comes out.

I installed the newest Wagtail and it seems the gallery worked just fine with it so I've increased the highest Wagtail version in the setup file and pushed out a new release.

If you use the newest gallery version (0.10.1), does it work fine for you?

**Comment by treefish** [comment]
Hello, yes, I have it working fine now. With a rebuild (in Docker), but just by using the latest in requirements.txt, all go. Thank you for being so active in responding. I'm now looking at a simple approach for creating a Wagtail Page that lists multiple image galleries for grouping related images (like albums or events), each with a bunch of images. I might start simple with a manual approach, and then see about automating it somewhat by having nested Collections and using Page Parent/Child logic.
So, yes, as far as I'm concerned, this issue is resolved. :-)
