### ISSUE TITLE
Ordering of images in a gallery

### ISSUE THREAD

**Issue by frague59** [Temeez/wagtail-simple-gallery#5]
Is there a way to order the gallery ? As I see, ordering is based on creation date, but wagtail provides an "Orderable" model mixin, that allows the ordering.

Do you think this kind of feature could be implemented ?

**Comment by NaakkaDev** [comment]
Currently there is no proper way to order the gallery. Do you want to order the admin view or public view (or both)?

I haven't done anything with wagtails "Orderable" model mixing so I don't know much about it, but I could look into it at some point this week, probably near the weekend.

Pull requests are always welcome of course. :)

**Comment by frague59** [comment]
The goal is to order images in the front.
I've used `Orderable` with placements, which permit to visually order items in
the admin site, and see them ordered according in the front.

I'll look at this later. I'm under pressure to deliver my current project,
I can't work on it for the next few weeks... I've many HTML / JS
adjustments on the way :o)

The idea could be:

+ Create a new model, `Orderable` with a 1to1 field to
`wagtailimages.Image`. This could be a way to not override the Image field

or

+ Override the `Image` model with `Orderable` but we have to build a
migration to move existing images from the `wagtailimages.Image` model

After that, update the admin to allow ordering of images. Both have to be
investigated...

**Comment by davnustratbac** [comment]
Hi Any news on this ? Im just looking at addressing the same issue, wondered if anyone had moved forward to avoid clashes with any future changes. Ive forked the app to try a few things. Incidentally Im running wagtail 12 with no problems so far, deployed to production with s3 storages. probably will submit a PR when im sure to bump version reqs in setup files. Regards D

**Comment by NaakkaDev** [comment]
@davnustratbac sorry for not responding sooner. I haven't done anything with this yet, but just now it occured to me that this could probably be done with the image tags, I'll look into it. I'm also going to update this to support the newest wagtail version soon when I find the time.

**Comment by NaakkaDev** [comment]
I added a crude way to order images on the gallery page. In the page content settings you can set the images to be ordered by image title which lets users to add "ordering numbers" to the image titles. For example `[0002] Cute cat`. I also added a template tag for hiding the `[<number>]` in the title.

I know that this is not very ideal but it's what I got for now.

**Comment by davnustratbac** [comment]
Hey no, thats great and thanks for taking the time and responding, Its
really appreciated. That will give the required ordering with little fuss,
Ill pull it down later and give it a whirl.
D

**Comment by frague59** [comment]
OK for me ! Thanks !
