### ISSUE TITLE
Use with Jinja2 template?

### ISSUE THREAD

**Issue by hongquan** [Temeez/wagtail-simple-gallery#6]
Is it possible to override template path for this app? I want to use my Jinja2 template (with extension _*.jinja_).

**Comment by NaakkaDev** [comment]
Do you want to override the template path in the `simple_gallery` inclusion tag? For that you could make your own template tag and change the template path. For example `@register.inclusion_tag('wagtail_simple_gallery/simple_gallery.jinja')` along with the TEMPLATES setting changes that django might require.

**Comment by hongquan** [comment]
@Temeez 
I want to override the template for `SimpleGalleryIndex` page type.

**Comment by NaakkaDev** [comment]
Ah I see. Have you seen [Jinja2 template support - Wagtail docs](http://docs.wagtail.io/en/v1.13.1/advanced_topics/jinja2.html#configuring-django)? If that doc doesn't help I can look into making it possible, somehow.

**Comment by hongquan** [comment]
Sadly, in Wagtail, the template is defined at `Page` model level. For instance:

```python
class HomePage(Page):
    template = 'home/home_page.jinja'
```

I cannot override `SimpleGalleryIndex`'s template that way.

**Comment by hongquan** [comment]
Hi, my request may cause break in your API. So I think I should have a "Django-version" of my Jinja template to serve `SimpleGalleryIndex`.

**Comment by NaakkaDev** [comment]
I added a `SIMPLE_GALLERY_TEMPLATE` setting so the `SimpleGalleryIndex` page template is easy to override without breaking anything. You should be able tell it to use your jinja2 template file without problems as long any django/Wagtail settings are configured properly.

For example: `SIMPLE_GALLERY_TEMPLATE = 'simple_gallery_index.jinja'`

**Comment by hongquan** [comment]
Oh, thank you.
