### ISSUE TITLE
Support for Wagtail 2.0 and Django 2.0

### ISSUE THREAD

**Issue by hongquan** [Temeez/wagtail-simple-gallery#7]
Hi,

Do you have time to make _wagtail-simple-gallery_ compatible with Wagtail 2.0 and Django 2.0?

Thanks.

**Comment by NaakkaDev** [comment]
Yeah. Nice timing as I was planning on doing that today or tomorrow. 😃

**Comment by hongquan** [comment]
Fortunately, it is rather simple to make _wagtail-simple-gallery_ compatible with Wagtail 2.0. I tried and have done it locally. Before making a PR, I want to ask some question:
- What is the version you want for this new update, 5.2?
- Do you need to be compatible with Wagtail < 2.0?

**Comment by NaakkaDev** [comment]
Oh nice.

- 0.6.0 (Since it doesn't need to support Wagtail < 2.0)
- No

**Comment by NaakkaDev** [comment]
Thank you @hongquan :)
I added a new setting value (check the readme) to handle the urls.py issue and uploaded v0.6.0 is in pypi.
